// Generated by scripts/update-managed-tools-manifest.ts.
// Do not edit checksums by hand.

import * as fs from "node:fs";

export interface ManagedToolTarget {
  platform: typeof process.platform;
  arch: typeof process.arch;
  asset: string;
  archive: "binary" | "tar.gz" | "tgz" | "zip";
  binName: string;
  sha256: string;
}

export interface ManagedToolManifestEntry {
  name: "actionlint" | "cloudflared" | "gitleaks" | "osv-scanner" | "ripgrep" | "trivy" | "zizmor";
  repo: string;
  version: string;
  source: string;
  generated_at: string;
  targets: ManagedToolTarget[];
}

export interface ManagedToolsManifest {
  schema_version: 1;
  generated_at: string;
  tools: {
    actionlint: ManagedToolManifestEntry;
    cloudflared: ManagedToolManifestEntry;
    gitleaks: ManagedToolManifestEntry;
    "osv-scanner": ManagedToolManifestEntry;
    ripgrep: ManagedToolManifestEntry;
    trivy: ManagedToolManifestEntry;
    zizmor: ManagedToolManifestEntry;
  };
}

export const MANAGED_TOOLS_MANIFEST: ManagedToolsManifest = {
  schema_version: 1,
  generated_at: "2026-05-01T00:58:10Z",
  tools: {
    actionlint: {
      name: "actionlint",
      repo: "rhysd/actionlint",
      version: "v1.7.12",
      source: "https://github.com/rhysd/actionlint/releases/tag/v1.7.12",
      generated_at: "2026-03-30T17:49:21Z",
      targets: [
        {
          platform: "darwin",
          arch: "arm64",
          asset: "actionlint_1.7.12_darwin_arm64.tar.gz",
          archive: "tar.gz",
          binName: "actionlint",
          sha256: "aba9ced2dee8d27fecca3dc7feb1a7f9a52caefa1eb46f3271ea66b6e0e6953f",
        },
        {
          platform: "darwin",
          arch: "x64",
          asset: "actionlint_1.7.12_darwin_amd64.tar.gz",
          archive: "tar.gz",
          binName: "actionlint",
          sha256: "5b44c3bc2255115c9b69e30efc0fecdf498fdb63c5d58e17084fd5f16324c644",
        },
        {
          platform: "linux",
          arch: "arm64",
          asset: "actionlint_1.7.12_linux_arm64.tar.gz",
          archive: "tar.gz",
          binName: "actionlint",
          sha256: "325e971b6ba9bfa504672e29be93c24981eeb1c07576d730e9f7c8805afff0c6",
        },
        {
          platform: "linux",
          arch: "x64",
          asset: "actionlint_1.7.12_linux_amd64.tar.gz",
          archive: "tar.gz",
          binName: "actionlint",
          sha256: "8aca8db96f1b94770f1b0d72b6dddcb1ebb8123cb3712530b08cc387b349a3d8",
        },
        {
          platform: "linux",
          arch: "ia32",
          asset: "actionlint_1.7.12_linux_386.tar.gz",
          archive: "tar.gz",
          binName: "actionlint",
          sha256: "72a44b32c2d032700e6d0c23ca2f540b67519ec68db098ddfcfa96059e61f723",
        },
        {
          platform: "linux",
          arch: "arm",
          asset: "actionlint_1.7.12_linux_armv6.tar.gz",
          archive: "tar.gz",
          binName: "actionlint",
          sha256: "ae4a0a5227578e66f5d00ee02788d5c64fdae1fa6484ab88ceaeee9359c28fa4",
        },
        {
          platform: "win32",
          arch: "arm64",
          asset: "actionlint_1.7.12_windows_arm64.zip",
          archive: "zip",
          binName: "actionlint.exe",
          sha256: "cadcf7ea4efe3a68728893813643cebe1185e5b1d4be5b96245f65c9a4d5ea41",
        },
        {
          platform: "win32",
          arch: "x64",
          asset: "actionlint_1.7.12_windows_amd64.zip",
          archive: "zip",
          binName: "actionlint.exe",
          sha256: "6e7241b51e6817ea6a047693d8e6fed13b31819c9a0dd6c5a726e1592d22f6e9",
        },
        {
          platform: "win32",
          arch: "ia32",
          asset: "actionlint_1.7.12_windows_386.zip",
          archive: "zip",
          binName: "actionlint.exe",
          sha256: "cdc8643b2c8dc890c76ad16095da97e75f86572805cc3573cc13f31ea0f19127",
        },
      ],
    },
    cloudflared: {
      name: "cloudflared",
      repo: "cloudflare/cloudflared",
      version: "2026.3.0",
      source: "https://github.com/cloudflare/cloudflared/releases/tag/2026.3.0",
      generated_at: "2026-03-09T14:17:29Z",
      targets: [
        {
          platform: "darwin",
          arch: "arm64",
          asset: "cloudflared-darwin-arm64.tgz",
          archive: "tgz",
          binName: "cloudflared",
          sha256: "2aae4f69b0fc1c671b8353b4f594cbd902cd1e360c8eed2b8cad4602cb1546fb",
        },
        {
          platform: "darwin",
          arch: "x64",
          asset: "cloudflared-darwin-amd64.tgz",
          archive: "tgz",
          binName: "cloudflared",
          sha256: "0f30140c4a5e213d22f951ef4c964cac5fb6a5f061ba6eba5ea932999f7c0394",
        },
        {
          platform: "linux",
          arch: "x64",
          asset: "cloudflared-linux-amd64",
          archive: "binary",
          binName: "cloudflared",
          sha256: "4a9e50e6d6d798e90fcd01933151a90bf7edd99a0a55c28ad18f2e16263a5c30",
        },
        {
          platform: "linux",
          arch: "arm64",
          asset: "cloudflared-linux-arm64",
          archive: "binary",
          binName: "cloudflared",
          sha256: "0755ba4cbab59980e6148367fcf53a8f3ec85a97deefd63c2420cf7850769bee",
        },
        {
          platform: "linux",
          arch: "ia32",
          asset: "cloudflared-linux-386",
          archive: "binary",
          binName: "cloudflared",
          sha256: "7d59f6ef7b4c255edd88187c74d2b4ecd895b6f5c4aca2cae0c4411eacebcbbd",
        },
        {
          platform: "linux",
          arch: "arm",
          asset: "cloudflared-linux-arm",
          archive: "binary",
          binName: "cloudflared",
          sha256: "ca16ed5253373846f7d366d591669d0e868e0724e35599abad2c8b2bc2340cfa",
        },
        {
          platform: "win32",
          arch: "x64",
          asset: "cloudflared-windows-amd64.exe",
          archive: "binary",
          binName: "cloudflared.exe",
          sha256: "59b12880b24af581cf5b1013db601c7d843b9b097e9c78aa5957c7f39f741885",
        },
        {
          platform: "win32",
          arch: "ia32",
          asset: "cloudflared-windows-386.exe",
          archive: "binary",
          binName: "cloudflared.exe",
          sha256: "e00a9e9fed12f8a8f5703539c4662750dd5472d35c16dcbbdc5869f3fe5e238b",
        },
      ],
    },
    gitleaks: {
      name: "gitleaks",
      repo: "gitleaks/gitleaks",
      version: "v8.30.1",
      source: "https://github.com/gitleaks/gitleaks/releases/tag/v8.30.1",
      generated_at: "2026-03-21T02:17:58Z",
      targets: [
        {
          platform: "darwin",
          arch: "arm64",
          asset: "gitleaks_8.30.1_darwin_arm64.tar.gz",
          archive: "tar.gz",
          binName: "gitleaks",
          sha256: "b40ab0ae55c505963e365f271a8d3846efbc170aa17f2607f13df610a9aeb6a5",
        },
        {
          platform: "darwin",
          arch: "x64",
          asset: "gitleaks_8.30.1_darwin_x64.tar.gz",
          archive: "tar.gz",
          binName: "gitleaks",
          sha256: "dfe101a4db2255fc85120ac7f3d25e4342c3c20cf749f2c20a18081af1952709",
        },
        {
          platform: "linux",
          arch: "arm64",
          asset: "gitleaks_8.30.1_linux_arm64.tar.gz",
          archive: "tar.gz",
          binName: "gitleaks",
          sha256: "e4a487ee7ccd7d3a7f7ec08657610aa3606637dab924210b3aee62570fb4b080",
        },
        {
          platform: "linux",
          arch: "x64",
          asset: "gitleaks_8.30.1_linux_x64.tar.gz",
          archive: "tar.gz",
          binName: "gitleaks",
          sha256: "551f6fc83ea457d62a0d98237cbad105af8d557003051f41f3e7ca7b3f2470eb",
        },
        {
          platform: "linux",
          arch: "ia32",
          asset: "gitleaks_8.30.1_linux_x32.tar.gz",
          archive: "tar.gz",
          binName: "gitleaks",
          sha256: "a87ba11adab22b4d6c6ea28b2da60f09154d5c2fdb44d4b07015d1e0433daecb",
        },
        {
          platform: "linux",
          arch: "arm",
          asset: "gitleaks_8.30.1_linux_armv7.tar.gz",
          archive: "tar.gz",
          binName: "gitleaks",
          sha256: "8d39f0d94ba0d774b2282187656fb039a2d82893ec1fd6be7d7121aae759a57d",
        },
        {
          platform: "win32",
          arch: "arm64",
          asset: "gitleaks_8.30.1_windows_arm64.zip",
          archive: "zip",
          binName: "gitleaks.exe",
          sha256: "b95f5e4f5c425cedca7ee203d9afd29597e692c4924a12ed42f970537c72cc0f",
        },
        {
          platform: "win32",
          arch: "x64",
          asset: "gitleaks_8.30.1_windows_x64.zip",
          archive: "zip",
          binName: "gitleaks.exe",
          sha256: "d29144deff3a68aa93ced33dddf84b7fdc26070add4aa0f4513094c8332afc4e",
        },
        {
          platform: "win32",
          arch: "ia32",
          asset: "gitleaks_8.30.1_windows_x32.zip",
          archive: "zip",
          binName: "gitleaks.exe",
          sha256: "190ad53db301eec3e90afe3a1a75270768b8ebf89e731345e19421c32c1ae1a1",
        },
      ],
    },
    ripgrep: {
      name: "ripgrep",
      repo: "BurntSushi/ripgrep",
      version: "15.1.0",
      source: "https://github.com/BurntSushi/ripgrep/releases/tag/15.1.0",
      generated_at: "2025-10-22T13:00:26Z",
      targets: [
        {
          platform: "darwin",
          arch: "arm64",
          asset: "ripgrep-15.1.0-aarch64-apple-darwin.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "378e973289176ca0c6054054ee7f631a065874a352bf43f0fa60ef079b6ba715",
        },
        {
          platform: "darwin",
          arch: "x64",
          asset: "ripgrep-15.1.0-x86_64-apple-darwin.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "64811cb24e77cac3057d6c40b63ac9becf9082eedd54ca411b475b755d334882",
        },
        {
          platform: "linux",
          arch: "arm64",
          asset: "ripgrep-15.1.0-aarch64-unknown-linux-gnu.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "2b661c6ef508e902f388e9098d9c4c5aca72c87b55922d94abdba830b4dc885e",
        },
        {
          platform: "linux",
          arch: "x64",
          asset: "ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "1c9297be4a084eea7ecaedf93eb03d058d6faae29bbc57ecdaf5063921491599",
        },
        {
          platform: "linux",
          arch: "ia32",
          asset: "ripgrep-15.1.0-i686-unknown-linux-gnu.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "0300c58864b1de49da08f714d56ce10328dcbf6de37a404486fe2696e95692f1",
        },
        {
          platform: "linux",
          arch: "arm",
          asset: "ripgrep-15.1.0-armv7-unknown-linux-gnueabihf.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "1349e515287c06317c1f7adc894a6590ab8bea8cbe997c61060bf6395f42733c",
        },
        {
          platform: "linux",
          arch: "s390x",
          asset: "ripgrep-15.1.0-s390x-unknown-linux-gnu.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "a7b9bae0009abc2df000877a2f6e64f03bbf8fdd0c912167427e69ab45dd2fef",
        },
        {
          platform: "win32",
          arch: "arm64",
          asset: "ripgrep-15.1.0-aarch64-pc-windows-msvc.zip",
          archive: "zip",
          binName: "rg.exe",
          sha256: "00d931fb5237c9696ca49308818edb76d8eb6fc132761cb2a1bd616b2df02f8e",
        },
        {
          platform: "win32",
          arch: "x64",
          asset: "ripgrep-15.1.0-x86_64-pc-windows-msvc.zip",
          archive: "zip",
          binName: "rg.exe",
          sha256: "124510b94b6baa3380d051fdf4650eaa80a302c876d611e9dba0b2e18d87493a",
        },
        {
          platform: "win32",
          arch: "ia32",
          asset: "ripgrep-15.1.0-i686-pc-windows-msvc.zip",
          archive: "zip",
          binName: "rg.exe",
          sha256: "725be85a1e8f92878a548f40ee4f6df64bc93b809586462b3c6d884e1de1e83a",
        },
      ],
    },
    "osv-scanner": {
      name: "osv-scanner",
      repo: "google/osv-scanner",
      version: "v2.3.6",
      source: "https://github.com/google/osv-scanner/releases/tag/v2.3.6",
      generated_at: "2026-05-01T00:58:10Z",
      targets: [
        {
          platform: "darwin",
          arch: "arm64",
          asset: "osv-scanner_darwin_arm64",
          archive: "binary",
          binName: "osv-scanner",
          sha256: "3d7a12f4349a9e8f822513e5544d4a747ab53b7225d4bf5a2d00211cbc9dfe19",
        },
        {
          platform: "darwin",
          arch: "x64",
          asset: "osv-scanner_darwin_amd64",
          archive: "binary",
          binName: "osv-scanner",
          sha256: "d5c91db387e0559b12136106bce5a57dbcea6fac22942721bd25b2334b28db28",
        },
        {
          platform: "linux",
          arch: "arm64",
          asset: "osv-scanner_linux_arm64",
          archive: "binary",
          binName: "osv-scanner",
          sha256: "e6ab0955cc906f308704575a608d28e55068d00c7fa7f47797131c89b30c0373",
        },
        {
          platform: "linux",
          arch: "x64",
          asset: "osv-scanner_linux_amd64",
          archive: "binary",
          binName: "osv-scanner",
          sha256: "f689e183ef0d573d2459738aae457d411a26241ae58b5088de1af288b3355604",
        },
        {
          platform: "win32",
          arch: "arm64",
          asset: "osv-scanner_windows_arm64.exe",
          archive: "binary",
          binName: "osv-scanner.exe",
          sha256: "5edd366ce55b696dbe74237987d8947808c400721b0cc4852f8224fbfd9f3c17",
        },
        {
          platform: "win32",
          arch: "x64",
          asset: "osv-scanner_windows_amd64.exe",
          archive: "binary",
          binName: "osv-scanner.exe",
          sha256: "14856196d681e18238b41d4741bbe0558bef157c4b3b49d618528294afebe19f",
        },
      ],
    },
    trivy: {
      name: "trivy",
      repo: "aquasecurity/trivy",
      version: "v0.70.0",
      source: "https://github.com/aquasecurity/trivy/releases/tag/v0.70.0",
      generated_at: "2026-04-17T06:50:02Z",
      targets: [
        {
          platform: "darwin",
          arch: "arm64",
          asset: "trivy_0.70.0_macOS-ARM64.tar.gz",
          archive: "tar.gz",
          binName: "trivy",
          sha256: "68e543c51dcc96e1c344053a4fde9660cf602c25565d9f09dc17dd41e13b838a",
        },
        {
          platform: "darwin",
          arch: "x64",
          asset: "trivy_0.70.0_macOS-64bit.tar.gz",
          archive: "tar.gz",
          binName: "trivy",
          sha256: "52d531452b19e7593da29366007d02a810e1e0080d02f9cf6a1afb46c35aaa93",
        },
        {
          platform: "linux",
          arch: "arm64",
          asset: "trivy_0.70.0_Linux-ARM64.tar.gz",
          archive: "tar.gz",
          binName: "trivy",
          sha256: "2f6bb988b553a1bbac6bdd1ce890f5e412439564e17522b88a4541b4f364fc8d",
        },
        {
          platform: "linux",
          arch: "x64",
          asset: "trivy_0.70.0_Linux-64bit.tar.gz",
          archive: "tar.gz",
          binName: "trivy",
          sha256: "8b4376d5d6befe5c24d503f10ff136d9e0c49f9127a4279fd110b727929a5aa9",
        },
        {
          platform: "linux",
          arch: "ia32",
          asset: "trivy_0.70.0_Linux-32bit.tar.gz",
          archive: "tar.gz",
          binName: "trivy",
          sha256: "b98d72c3a81ae13ace8f45e4710089087ede421deead5ab8842d51103ca7b3d9",
        },
        {
          platform: "linux",
          arch: "arm",
          asset: "trivy_0.70.0_Linux-ARM.tar.gz",
          archive: "tar.gz",
          binName: "trivy",
          sha256: "12537cc6bf3f45e28e0b6b8bea0382ec9fabb468e0c3372e376474d5002c2ffe",
        },
        {
          platform: "linux",
          arch: "s390x",
          asset: "trivy_0.70.0_Linux-s390x.tar.gz",
          archive: "tar.gz",
          binName: "trivy",
          sha256: "92ec9caffdcc32d43b76d21d4ecd6ea2975a2b37e050d5f79e17651c490b1753",
        },
        {
          platform: "win32",
          arch: "x64",
          asset: "trivy_0.70.0_windows-64bit.zip",
          archive: "zip",
          binName: "trivy.exe",
          sha256: "eea5442eab86f9e26cd718d7618d43899e72a83767619e8bee47911bddbfb825",
        },
      ],
    },
    zizmor: {
      name: "zizmor",
      repo: "zizmorcore/zizmor",
      version: "v1.24.1",
      source: "https://github.com/zizmorcore/zizmor/releases/tag/v1.24.1",
      generated_at: "2026-04-13T18:25:21Z",
      targets: [
        {
          platform: "darwin",
          arch: "arm64",
          asset: "zizmor-aarch64-apple-darwin.tar.gz",
          archive: "tar.gz",
          binName: "zizmor",
          sha256: "fc4ea59e18bc028dddb5f710b16dbc361b01ff1e7a20c03b8e5778366ca9f4e1",
        },
        {
          platform: "darwin",
          arch: "x64",
          asset: "zizmor-x86_64-apple-darwin.tar.gz",
          archive: "tar.gz",
          binName: "zizmor",
          sha256: "721ba70d7fca753aeef1a4ee959a9bc20c55784d4faa6c56e66129a2611fd52f",
        },
        {
          platform: "linux",
          arch: "arm64",
          asset: "zizmor-aarch64-unknown-linux-gnu.tar.gz",
          archive: "tar.gz",
          binName: "zizmor",
          sha256: "d66e37ef8a375fb07939c630ebf9709a6e0f20242bdc3faf672a7ed97e0b768d",
        },
        {
          platform: "linux",
          arch: "x64",
          asset: "zizmor-x86_64-unknown-linux-gnu.tar.gz",
          archive: "tar.gz",
          binName: "zizmor",
          sha256: "a8000f3c683319a523d3b20df0e75457ba591f049cfcbfa98966631b56733c03",
        },
        {
          platform: "win32",
          arch: "x64",
          asset: "zizmor-x86_64-pc-windows-msvc.zip",
          archive: "zip",
          binName: "zizmor.exe",
          sha256: "b777ec2cb1098139ba74b32e30d11ed149c69ab692d23788c466d4a31704bd4b",
        },
      ],
    },
  },
};

export function managedToolTarget(
  tool: keyof ManagedToolsManifest["tools"],
  platform: typeof process.platform = process.platform,
  arch: typeof process.arch = process.arch,
): ManagedToolTarget | null {
  return (
    MANAGED_TOOLS_MANIFEST.tools[tool].targets.find(
      (target) => target.platform === platform && target.arch === arch,
    ) ?? null
  );
}

/**
 * Detect a musl-libc Linux host (most commonly Alpine).
 *
 * The shipped managed-tool manifest only carries glibc Linux assets for
 * `gitleaks` and `zizmor` — those tarballs link against glibc and fail to
 * exec on musl with an opaque "not found" error from the dynamic linker.
 * This helper lets callers throw a clear Unsupported error before
 * downloading a binary that cannot run.
 *
 * Detection order (cheap first, no shell-out):
 *   1. `process.report.getReport().header.glibcVersionRuntime` is absent on musl.
 *   2. `/etc/alpine-release` exists on Alpine.
 *
 * Override knob:
 *   `VEGASTACK_FORCE_LIBC=glibc|musl` skips detection (used by tests + the
 *   `npm run smoke:managed-tools` matrix).
 */
export function detectLinuxLibc(
  platform: typeof process.platform = process.platform,
): "glibc" | "musl" | "unknown" {
  if (platform !== "linux") return "unknown";
  const override = process.env.VEGASTACK_FORCE_LIBC;
  if (override === "glibc" || override === "musl") return override;
  try {
    const report = (process as unknown as { report?: { getReport?: () => unknown } }).report;
    const got = report?.getReport?.() as
      | { header?: { glibcVersionRuntime?: string } }
      | undefined;
    if (got?.header && typeof got.header.glibcVersionRuntime === "string") return "glibc";
    if (got?.header && got.header.glibcVersionRuntime === undefined) {
      // Header is present but the field is absent → musl-built Node.
      return "musl";
    }
  } catch {
    // fall through to fs probe
  }
  try {
    if (fs.existsSync("/etc/alpine-release")) return "musl";
  } catch {
    /* ignore */
  }
  return "unknown";
}

/**
 * Throw an Unsupported-shaped error (caller wraps in VegaStackError) if the
 * given managed tool has no asset for this host's libc. Today this only
 * fires on Alpine for `gitleaks` and `zizmor`, which ship glibc-only assets.
 *
 * Returns the user-facing remediation string in the error message so the
 * `printError` shim renders a clear stderr line to operators on Alpine.
 */
export function assertManagedToolLibcSupported(
  tool: keyof ManagedToolsManifest["tools"],
  platform: typeof process.platform = process.platform,
): void {
  if (platform !== "linux") return;
  if (detectLinuxLibc(platform) !== "musl") return;
  // ripgrep ships an explicit musl asset; the rest are glibc-only on linux.
  if (tool === "ripgrep") return;
  throw Object.assign(
    new Error(
      `managed ${tool} has no musl/Alpine build; install ${tool} via apk and set ` +
        `VEGASTACK_ALLOW_SYSTEM_TOOLS=1, or run on a glibc distro. ` +
        `See docs: cross-platform.md#alpine-musl.`,
    ),
    { code: "VegaStackError", kind: "Unsupported" },
  );
}
