// Generated by scripts/update-managed-tools-manifest.ts.
// Do not edit checksums by hand.

type ManagedToolPlatform = typeof process.platform;
type ManagedToolArchitecture = typeof process.arch;

export interface ManagedToolTarget {
  platform: ManagedToolPlatform;
  arch: ManagedToolArchitecture;
  asset: string;
  archive: "binary" | "tar.gz" | "tgz" | "zip";
  binName: string;
  sha256: string;
}

export interface ManagedToolManifestEntry {
  name: "cloudflared" | "gitleaks" | "ripgrep";
  repo: string;
  version: string;
  source: string;
  generated_at: string;
  targets: ManagedToolTarget[];
}

export interface ManagedToolsManifest {
  schema_version: 1;
  generated_at: string;
  tools: {
    cloudflared: ManagedToolManifestEntry;
    gitleaks: ManagedToolManifestEntry;
    ripgrep: ManagedToolManifestEntry;
  };
}

export const MANAGED_TOOLS_MANIFEST: ManagedToolsManifest = {
  schema_version: 1,
  generated_at: "2026-03-21T02:17:58Z",
  tools: {
    cloudflared: {
      name: "cloudflared",
      repo: "cloudflare/cloudflared",
      version: "2026.3.0",
      source: "https://github.com/cloudflare/cloudflared/releases/tag/2026.3.0",
      generated_at: "2026-03-09T14:17:29Z",
      targets: [
        {
          platform: "darwin",
          arch: "arm64",
          asset: "cloudflared-darwin-arm64.tgz",
          archive: "tgz",
          binName: "cloudflared",
          sha256: "2aae4f69b0fc1c671b8353b4f594cbd902cd1e360c8eed2b8cad4602cb1546fb",
        },
        {
          platform: "darwin",
          arch: "x64",
          asset: "cloudflared-darwin-amd64.tgz",
          archive: "tgz",
          binName: "cloudflared",
          sha256: "0f30140c4a5e213d22f951ef4c964cac5fb6a5f061ba6eba5ea932999f7c0394",
        },
        {
          platform: "linux",
          arch: "x64",
          asset: "cloudflared-linux-amd64",
          archive: "binary",
          binName: "cloudflared",
          sha256: "4a9e50e6d6d798e90fcd01933151a90bf7edd99a0a55c28ad18f2e16263a5c30",
        },
        {
          platform: "linux",
          arch: "arm64",
          asset: "cloudflared-linux-arm64",
          archive: "binary",
          binName: "cloudflared",
          sha256: "0755ba4cbab59980e6148367fcf53a8f3ec85a97deefd63c2420cf7850769bee",
        },
        {
          platform: "linux",
          arch: "ia32",
          asset: "cloudflared-linux-386",
          archive: "binary",
          binName: "cloudflared",
          sha256: "7d59f6ef7b4c255edd88187c74d2b4ecd895b6f5c4aca2cae0c4411eacebcbbd",
        },
        {
          platform: "linux",
          arch: "arm",
          asset: "cloudflared-linux-arm",
          archive: "binary",
          binName: "cloudflared",
          sha256: "ca16ed5253373846f7d366d591669d0e868e0724e35599abad2c8b2bc2340cfa",
        },
        {
          platform: "win32",
          arch: "x64",
          asset: "cloudflared-windows-amd64.exe",
          archive: "binary",
          binName: "cloudflared.exe",
          sha256: "59b12880b24af581cf5b1013db601c7d843b9b097e9c78aa5957c7f39f741885",
        },
        {
          platform: "win32",
          arch: "ia32",
          asset: "cloudflared-windows-386.exe",
          archive: "binary",
          binName: "cloudflared.exe",
          sha256: "e00a9e9fed12f8a8f5703539c4662750dd5472d35c16dcbbdc5869f3fe5e238b",
        },
      ],
    },
    gitleaks: {
      name: "gitleaks",
      repo: "gitleaks/gitleaks",
      version: "v8.30.1",
      source: "https://github.com/gitleaks/gitleaks/releases/tag/v8.30.1",
      generated_at: "2026-03-21T02:17:58Z",
      targets: [
        {
          platform: "darwin",
          arch: "arm64",
          asset: "gitleaks_8.30.1_darwin_arm64.tar.gz",
          archive: "tar.gz",
          binName: "gitleaks",
          sha256: "b40ab0ae55c505963e365f271a8d3846efbc170aa17f2607f13df610a9aeb6a5",
        },
        {
          platform: "darwin",
          arch: "x64",
          asset: "gitleaks_8.30.1_darwin_x64.tar.gz",
          archive: "tar.gz",
          binName: "gitleaks",
          sha256: "dfe101a4db2255fc85120ac7f3d25e4342c3c20cf749f2c20a18081af1952709",
        },
        {
          platform: "linux",
          arch: "arm64",
          asset: "gitleaks_8.30.1_linux_arm64.tar.gz",
          archive: "tar.gz",
          binName: "gitleaks",
          sha256: "e4a487ee7ccd7d3a7f7ec08657610aa3606637dab924210b3aee62570fb4b080",
        },
        {
          platform: "linux",
          arch: "x64",
          asset: "gitleaks_8.30.1_linux_x64.tar.gz",
          archive: "tar.gz",
          binName: "gitleaks",
          sha256: "551f6fc83ea457d62a0d98237cbad105af8d557003051f41f3e7ca7b3f2470eb",
        },
        {
          platform: "linux",
          arch: "ia32",
          asset: "gitleaks_8.30.1_linux_x32.tar.gz",
          archive: "tar.gz",
          binName: "gitleaks",
          sha256: "a87ba11adab22b4d6c6ea28b2da60f09154d5c2fdb44d4b07015d1e0433daecb",
        },
        {
          platform: "linux",
          arch: "arm",
          asset: "gitleaks_8.30.1_linux_armv7.tar.gz",
          archive: "tar.gz",
          binName: "gitleaks",
          sha256: "8d39f0d94ba0d774b2282187656fb039a2d82893ec1fd6be7d7121aae759a57d",
        },
        {
          platform: "win32",
          arch: "arm64",
          asset: "gitleaks_8.30.1_windows_arm64.zip",
          archive: "zip",
          binName: "gitleaks.exe",
          sha256: "b95f5e4f5c425cedca7ee203d9afd29597e692c4924a12ed42f970537c72cc0f",
        },
        {
          platform: "win32",
          arch: "x64",
          asset: "gitleaks_8.30.1_windows_x64.zip",
          archive: "zip",
          binName: "gitleaks.exe",
          sha256: "d29144deff3a68aa93ced33dddf84b7fdc26070add4aa0f4513094c8332afc4e",
        },
        {
          platform: "win32",
          arch: "ia32",
          asset: "gitleaks_8.30.1_windows_x32.zip",
          archive: "zip",
          binName: "gitleaks.exe",
          sha256: "190ad53db301eec3e90afe3a1a75270768b8ebf89e731345e19421c32c1ae1a1",
        },
      ],
    },
    ripgrep: {
      name: "ripgrep",
      repo: "BurntSushi/ripgrep",
      version: "15.1.0",
      source: "https://github.com/BurntSushi/ripgrep/releases/tag/15.1.0",
      generated_at: "2025-10-22T13:00:26Z",
      targets: [
        {
          platform: "darwin",
          arch: "arm64",
          asset: "ripgrep-15.1.0-aarch64-apple-darwin.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "378e973289176ca0c6054054ee7f631a065874a352bf43f0fa60ef079b6ba715",
        },
        {
          platform: "darwin",
          arch: "x64",
          asset: "ripgrep-15.1.0-x86_64-apple-darwin.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "64811cb24e77cac3057d6c40b63ac9becf9082eedd54ca411b475b755d334882",
        },
        {
          platform: "linux",
          arch: "arm64",
          asset: "ripgrep-15.1.0-aarch64-unknown-linux-gnu.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "2b661c6ef508e902f388e9098d9c4c5aca72c87b55922d94abdba830b4dc885e",
        },
        {
          platform: "linux",
          arch: "x64",
          asset: "ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "1c9297be4a084eea7ecaedf93eb03d058d6faae29bbc57ecdaf5063921491599",
        },
        {
          platform: "linux",
          arch: "ia32",
          asset: "ripgrep-15.1.0-i686-unknown-linux-gnu.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "0300c58864b1de49da08f714d56ce10328dcbf6de37a404486fe2696e95692f1",
        },
        {
          platform: "linux",
          arch: "arm",
          asset: "ripgrep-15.1.0-armv7-unknown-linux-gnueabihf.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "1349e515287c06317c1f7adc894a6590ab8bea8cbe997c61060bf6395f42733c",
        },
        {
          platform: "linux",
          arch: "s390x",
          asset: "ripgrep-15.1.0-s390x-unknown-linux-gnu.tar.gz",
          archive: "tar.gz",
          binName: "rg",
          sha256: "a7b9bae0009abc2df000877a2f6e64f03bbf8fdd0c912167427e69ab45dd2fef",
        },
        {
          platform: "win32",
          arch: "arm64",
          asset: "ripgrep-15.1.0-aarch64-pc-windows-msvc.zip",
          archive: "zip",
          binName: "rg.exe",
          sha256: "00d931fb5237c9696ca49308818edb76d8eb6fc132761cb2a1bd616b2df02f8e",
        },
        {
          platform: "win32",
          arch: "x64",
          asset: "ripgrep-15.1.0-x86_64-pc-windows-msvc.zip",
          archive: "zip",
          binName: "rg.exe",
          sha256: "124510b94b6baa3380d051fdf4650eaa80a302c876d611e9dba0b2e18d87493a",
        },
        {
          platform: "win32",
          arch: "ia32",
          asset: "ripgrep-15.1.0-i686-pc-windows-msvc.zip",
          archive: "zip",
          binName: "rg.exe",
          sha256: "725be85a1e8f92878a548f40ee4f6df64bc93b809586462b3c6d884e1de1e83a",
        },
      ],
    },
  },
};

export function managedToolTarget(
  tool: keyof ManagedToolsManifest["tools"],
  platform: ManagedToolPlatform = process.platform,
  arch: ManagedToolArchitecture = process.arch,
): ManagedToolTarget | null {
  return (
    MANAGED_TOOLS_MANIFEST.tools[tool].targets.find(
      (target) => target.platform === platform && target.arch === arch,
    ) ?? null
  );
}
