// src/agents/gemini.ts
//
// Gemini CLI renderer.
//
// Per geminicli.com/docs/extensions/reference (April 2026), an extension
// installs to `~/.gemini/extensions/<name>/` and contains:
//
//   gemini-extension.json   — extension manifest (name, version, mcpServers, ...)
//   skills/<id>/SKILL.md    — Anthropic-style skill (Gemini reads SKILL.md too)
//   commands/tf.toml        — registers a /tf slash command
//
// We support both `--scope global` (writes under HOME) and `--scope project`
// (writes under cwd/.gemini/extensions/), though global is the documented
// install target for shared extensions.

import * as fs from "node:fs";
import * as path from "node:path";

import {
  DestinationExistsError,
  copyFileWithBackup,
  existsOrLink,
  removeIfExists,
} from "../lib/fs-utils.js";
import {
  geminiContextPath,
  geminiExtensionPath,
  geminiExtensionRoot,
  pkgCanonicalSkillMd,
  pkgGeminiContext,
  pkgGeminiExtension,
} from "../lib/paths.js";
import type {
  AgentInstaller,
  AgentRenderer,
  InstallContext,
  InstallResult,
  Scope,
} from "./types.js";

const COMMAND_TOML = `# /tf — search Terraform docs (vegastack tf <query>)
# Generated by @vegastack/cli; do not hand-edit.

description = "Search Terraform docs (local, deterministic, no network)."
prompt = """
Run \`vegastack tf "{{args}}"\` and read the returned JSON envelope on stdout. The
envelope has four channels: knowledge[] (recent-change cards — read first if
overrides_training is true), recipes[] (cross-provider topology scaffolds),
files[] (top-K resource docs with manifest_entry + example_usage inline), and
concept_aliases_used[] (NL phrase to resource mapping).

End your reply with the citations[] array verbatim — relative file paths plus
any knowledge-card / recipe IDs you used.
"""
`;

class GeminiRenderer implements AgentRenderer {
  readonly name = "gemini";
  readonly displayName = "Gemini CLI";

  supportsScope(_scope: Scope): boolean {
    return true;
  }

  async status(ctx: InstallContext): Promise<InstallResult> {
    const root = geminiExtensionRoot(ctx.scope, ctx.cwd);
    const extJson = path.join(root, "gemini-extension.json");
    const skillMd = path.join(root, "skills", "vegastack", "SKILL.md");
    const cmdToml = path.join(root, "commands", "tf.toml");
    const all = [extJson, skillMd, cmdToml];
    const present = all.every((p) => existsOrLink(p));
    return {
      agent: this.name,
      installed: present,
      paths: all,
      notes: present
        ? ["Extension config, SKILL.md and /tf command all present."]
        : [`Missing one or more of ${all.join(", ")}.`],
      warnings: [],
    };
  }

  async install(ctx: InstallContext): Promise<InstallResult> {
    const root = geminiExtensionRoot(ctx.scope, ctx.cwd);
    const extJson = path.join(root, "gemini-extension.json");
    const skillMd = path.join(root, "skills", "vegastack", "SKILL.md");
    const cmdToml = path.join(root, "commands", "tf.toml");

    const result: InstallResult = {
      agent: this.name,
      installed: false,
      paths: [extJson, skillMd, cmdToml],
      notes: [],
      warnings: [],
    };

    if (ctx.dryRun) {
      result.notes.push(`would write ${extJson}`);
      result.notes.push(`would write ${skillMd}`);
      result.notes.push(`would write ${cmdToml}`);
      return result;
    }

    fs.mkdirSync(path.dirname(extJson), { recursive: true });
    fs.mkdirSync(path.dirname(skillMd), { recursive: true });
    fs.mkdirSync(path.dirname(cmdToml), { recursive: true });

    const extPayload = fs.readFileSync(pkgGeminiExtension(), "utf8");
    const skillPayload = fs.readFileSync(pkgCanonicalSkillMd(), "utf8");

    writeIfChanged(extJson, extPayload, ctx.force, result);
    writeIfChanged(skillMd, skillPayload, ctx.force, result);
    writeIfChanged(cmdToml, COMMAND_TOML, ctx.force, result);

    if (result.warnings.length === 0) {
      result.installed = true;
      result.notes.push("Run /tf in Gemini CLI to invoke. Reload via `gemini extensions list`.");
    }
    return result;
  }

  async uninstall(ctx: InstallContext): Promise<InstallResult> {
    const root = geminiExtensionRoot(ctx.scope, ctx.cwd);
    const result: InstallResult = {
      agent: this.name,
      installed: false,
      paths: [root],
      notes: [],
      warnings: [],
    };
    if (!existsOrLink(root)) {
      result.notes.push("nothing to remove (not installed).");
      return result;
    }
    if (ctx.dryRun) {
      result.notes.push(`would remove ${root}`);
      return result;
    }
    removeIfExists(root);
    result.notes.push(`removed ${root}`);
    return result;
  }
}

function writeIfChanged(
  dest: string,
  payload: string,
  force: boolean,
  result: InstallResult,
): void {
  let onDisk: string | null = null;
  try {
    onDisk = fs.readFileSync(dest, "utf8");
  } catch {
    /* absent */
  }
  if (onDisk === payload) {
    result.notes.push(`up to date: ${dest}`);
    return;
  }
  if (onDisk !== null && !force) {
    result.warnings.push(`destination exists and differs; pass --force to overwrite: ${dest}`);
    return;
  }
  fs.writeFileSync(dest, payload, "utf8");
  result.notes.push(onDisk === null ? `wrote ${dest}` : `overwrote ${dest}`);
}

export const geminiRenderer: AgentRenderer = new GeminiRenderer();

// ── Legacy synchronous installer (project-cwd layout, kept for back-compat) ──
//
// The legacy layout drops `gemini-extension.json` and `CONTEXT.md` directly
// into the user's project cwd. That worked for early Gemini Code Assist
// adopters and the existing `vegastack skills install` command depends on it.
// New consumers should target the AgentRenderer above (modern layout under
// `~/.gemini/extensions/vegastack/`).

class GeminiInstaller implements AgentInstaller {
  readonly name = "gemini";
  readonly displayName = "Gemini Code Assist";

  supportsScope(scope: Scope): boolean {
    return scope === "project";
  }

  status(ctx: InstallContext): InstallResult {
    const ext = geminiExtensionPath(ctx.cwd);
    const ctxMd = geminiContextPath(ctx.cwd);
    const both = fs.existsSync(ext) && fs.existsSync(ctxMd);
    return {
      agent: this.name,
      installed: both,
      paths: [ext, ctxMd],
      notes: both
        ? ["Both extension config and CONTEXT.md present."]
        : [
            `Need both files. extension=${fs.existsSync(ext) ? "ok" : "missing"}, context=${fs.existsSync(ctxMd) ? "ok" : "missing"}`,
          ],
      warnings: [],
    };
  }

  install(ctx: InstallContext): InstallResult {
    if (!this.supportsScope(ctx.scope)) {
      return {
        agent: this.name,
        installed: false,
        paths: [],
        notes: [],
        warnings: ["Gemini extension is project-scoped only. Run inside the project dir."],
      };
    }
    const extDst = geminiExtensionPath(ctx.cwd);
    const ctxDst = geminiContextPath(ctx.cwd);
    const result: InstallResult = {
      agent: this.name,
      installed: false,
      paths: [extDst, ctxDst],
      notes: [],
      warnings: [],
    };

    if (ctx.dryRun) {
      result.notes.push(`would write ${extDst} (with backup if it exists)`);
      result.notes.push(`would write ${ctxDst} (with backup if it exists)`);
      return result;
    }

    let allWritten = true;
    for (const [src, dst, label] of [
      [pkgGeminiExtension(), extDst, "gemini-extension.json"],
      [pkgGeminiContext(), ctxDst, "CONTEXT.md"],
    ] as const) {
      try {
        const backup = copyFileWithBackup(src, dst, { force: ctx.force });
        if (backup) result.notes.push(`backed up existing ${label} → ${backup}, then wrote ours`);
        else result.notes.push(`wrote ${dst}`);
      } catch (e) {
        if (e instanceof DestinationExistsError) {
          result.warnings.push(
            `skipping ${label} (exists; pass --force to overwrite with backup): ${dst}`,
          );
          allWritten = false;
        } else {
          throw e;
        }
      }
    }

    if (allWritten) {
      result.installed = true;
      result.notes.push("Gemini Code Assist will read the context on next session.");
    }
    return result;
  }

  uninstall(ctx: InstallContext): InstallResult {
    const result: InstallResult = {
      agent: this.name,
      installed: false,
      paths: [],
      notes: [],
      warnings: [],
    };
    const removed: string[] = [];
    for (const p of [geminiExtensionPath(ctx.cwd), geminiContextPath(ctx.cwd)]) {
      if (existsOrLink(p)) {
        if (!ctx.dryRun) removeIfExists(p);
        removed.push(p);
      }
    }
    if (removed.length === 0) {
      result.notes.push("nothing to remove (not installed).");
    } else {
      result.notes.push(
        ctx.dryRun ? `would remove ${removed.join(", ")}` : `removed ${removed.join(", ")}`,
      );
    }
    result.paths = removed;
    return result;
  }
}

export const gemini: AgentInstaller = new GeminiInstaller();
