// src/agents/gemini.ts
//
// Gemini CLI renderer.
//
// Per geminicli.com/docs/extensions/reference (April 2026), an extension
// installs to `~/.gemini/extensions/<name>/` and contains:
//
//   gemini-extension.json   — extension manifest (name, version, mcpServers, ...)
//   skills/<id>/SKILL.md    — Anthropic-style skill (Gemini reads SKILL.md too)
//   commands/vegastack.toml — registers a /vegastack slash command
//
// We support both `--scope global` (writes under HOME) and `--scope project`
// (writes under cwd/.gemini/extensions/), though global is the documented
// install target for shared extensions.

import * as fs from "node:fs";
import * as path from "node:path";

import { existsOrLink, removeIfExists } from "../lib/fs-utils.js";
import { geminiExtensionRoot, pkgCanonicalSkillMd, pkgGeminiExtension } from "../lib/paths.js";
import type { AgentRenderer, InstallContext, InstallResult, Scope } from "./types.js";

const COMMAND_TOML = `# /vegastack - VegaStack ops command router
# Generated by @vegastack/cli; do not hand-edit.

description = "Run the VegaStack ops router for init, ask, scan, search, doctor, update, preview, and tunnel workflows."
prompt = """
Use the bundled vegastack skill instructions for "{{args}}". Route the first
word as a subcommand when it is one of init, ask, scan, search, doctor, update,
preview, or tunnel. Use VegaStack CLI as the source of truth and prefer
non-interactive flags such as --yes and --agent after resolving user preferences.
"""
`;

class GeminiRenderer implements AgentRenderer {
  readonly name = "gemini";
  readonly displayName = "Gemini CLI";

  supportsScope(_scope: Scope): boolean {
    return true;
  }

  async status(ctx: InstallContext): Promise<InstallResult> {
    const root = geminiExtensionRoot(ctx.scope, ctx.cwd);
    const extJson = path.join(root, "gemini-extension.json");
    const skillMd = path.join(root, "skills", "vegastack", "SKILL.md");
    const cmdToml = path.join(root, "commands", "vegastack.toml");
    const all = [extJson, skillMd, cmdToml];
    const present = all.every((p) => existsOrLink(p));
    return {
      agent: this.name,
      installed: present,
      paths: all,
      notes: present
        ? ["Extension config, SKILL.md and /vegastack command all present."]
        : [`Missing one or more of ${all.join(", ")}.`],
      warnings: [],
    };
  }

  async install(ctx: InstallContext): Promise<InstallResult> {
    const root = geminiExtensionRoot(ctx.scope, ctx.cwd);
    const extJson = path.join(root, "gemini-extension.json");
    const skillMd = path.join(root, "skills", "vegastack", "SKILL.md");
    const cmdToml = path.join(root, "commands", "vegastack.toml");

    const result: InstallResult = {
      agent: this.name,
      installed: false,
      paths: [extJson, skillMd, cmdToml],
      notes: [],
      warnings: [],
    };

    if (ctx.dryRun) {
      result.notes.push(`would write ${extJson}`);
      result.notes.push(`would write ${skillMd}`);
      result.notes.push(`would write ${cmdToml}`);
      return result;
    }

    const extPayload = fs.readFileSync(pkgGeminiExtension(), "utf8");
    const skillPayload = fs.readFileSync(pkgCanonicalSkillMd(), "utf8");

    // Audit F-003: install must be atomic. Pre-flight every target file:
    // if any required write would be blocked (existing-and-different without
    // --force), refuse to write any of them so the on-disk state never
    // straddles a half-installed extension. Without this, a user with a
    // hand-edited `gemini-extension.json` (warning) and missing SKILL.md
    // could end up with our SKILL.md and command.toml on disk while
    // `installed: false` was still reported.
    const targets: { dest: string; payload: string }[] = [
      { dest: extJson, payload: extPayload },
      { dest: skillMd, payload: skillPayload },
      { dest: cmdToml, payload: COMMAND_TOML },
    ];
    const conflicts: string[] = [];
    for (const t of targets) {
      let onDisk: string | null = null;
      try {
        onDisk = fs.readFileSync(t.dest, "utf8");
      } catch {
        /* absent — safe to write */
      }
      if (onDisk !== null && onDisk !== t.payload && !ctx.force) {
        conflicts.push(t.dest);
      }
    }
    if (conflicts.length > 0) {
      for (const c of conflicts) {
        result.warnings.push(`destination exists and differs; pass --force to overwrite: ${c}`);
      }
      return result;
    }

    fs.mkdirSync(path.dirname(extJson), { recursive: true });
    fs.mkdirSync(path.dirname(skillMd), { recursive: true });
    fs.mkdirSync(path.dirname(cmdToml), { recursive: true });

    for (const t of targets) {
      writeIfChanged(t.dest, t.payload, ctx.force, result);
    }

    if (result.warnings.length === 0) {
      result.installed = true;
      result.notes.push(
        "Run /vegastack in Gemini CLI to invoke. Reload via `gemini extensions list`.",
      );
    }
    return result;
  }

  async uninstall(ctx: InstallContext): Promise<InstallResult> {
    const root = geminiExtensionRoot(ctx.scope, ctx.cwd);
    const result: InstallResult = {
      agent: this.name,
      installed: false,
      paths: [root],
      notes: [],
      warnings: [],
    };
    if (!existsOrLink(root)) {
      result.notes.push("nothing to remove (not installed).");
      return result;
    }
    if (ctx.dryRun) {
      result.notes.push(`would remove ${root}`);
      return result;
    }
    removeIfExists(root);
    result.notes.push(`removed ${root}`);
    return result;
  }
}

function writeIfChanged(
  dest: string,
  payload: string,
  force: boolean,
  result: InstallResult,
): void {
  let onDisk: string | null = null;
  try {
    onDisk = fs.readFileSync(dest, "utf8");
  } catch {
    /* absent */
  }
  if (onDisk === payload) {
    result.notes.push(`up to date: ${dest}`);
    return;
  }
  if (onDisk !== null && !force) {
    result.warnings.push(`destination exists and differs; pass --force to overwrite: ${dest}`);
    return;
  }
  fs.writeFileSync(dest, payload, "utf8");
  result.notes.push(onDisk === null ? `wrote ${dest}` : `overwrote ${dest}`);
}

export const geminiRenderer: AgentRenderer = new GeminiRenderer();
